name: Build and Push Golang Docker Image

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Memastikan tag mengikuti format semver

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: PLAYGROUND

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/example_app
          tags: |
            type=semver,pattern={{version}}

      - name: Log in to Docker Hub
        id: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        if: steps.docker_login.outcome == 'success'
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
